### ISSUE TITLE
Dataloader: Incorrect dataspec file created for multiple environments

### ISSUE THREAD

**Issue by akashsharma02** [castacks/tartanairpy#31]
When a Dataloader is created with files to be loaded from multiple environments, the config created in `get_data_cacher` function only stores a dataspec for the last environment. This is problematic because

1. `Multidatasets` class uses the number of `"data"` entries to calculate the total number of datasets / dataloaders. 
2. `load_sample` randomly samples a dataset based on the total number of datasets, which always remains 1, resulting in samples only from one environment.

Is this a problem, or is this expected?

**Comment by yoraish** [comment]
Thanks for starting this issue!

Could you please add an example of when this happens? Perhaps download two small environments and ask to load data from both? What you are describing is not the intended behavior and I do not see it reflected on my side.

In some more detail: the `ta_data_spec.txt` file that is automatically created by the TartanAir Dataloader (under the hood the Data Cacher indeed) stores specifications for all images (and other enumerated data files) from all the requested trajectories. You will see each trajectory being split into smaller chunks, for shuffling purposes. This might not be in line with what you need/expect and we can discuss this further. But generally all of the data you request should be loaded.

Regarding your specific points:
1. We compile the subset of TartanAir that you request into a single "dataset", which is why you see `1` in the `Multidatasets`. This does not mean a single environment, but rather a single data spec file (which in our case enumerates data from multiple environments).
2. Samples should be drawn from multiple environments, if those have been requested. Could you please verify that you are only getting samples from a single environment? And if you do, please share the code snippets so we could debug on our side :).

**Comment by akashsharma02** [comment]
Apologies for the late response, I got a bit occupied with other commitments! You are right and the data loading is correct, but internally the total number of datasets remains 1, which is an implementation detail.
